### ISSUE TITLE
Please advise if you have plans or if this works with nextcloud 21

### ISSUE THREAD

**Issue by jetadidas** [nextcloud/end_to_end_encryption#226] opened 2021-03-01 20:05 UTC
Please advise if you of plans or if this is working with nextcloud 21 and php8. Would be much appreciated thank you and have a great day

**Comment by wheeljack73** [comment] 2021-03-02 16:20
Not working for me.  Seems to install but not enable - some random error when doing through NextCloud UI.
In CLI using OCC, I get the following error:

`Error: Undefined class constant 'BIGINT' in /home/<hidden>/public_html/apps/end_to_end_encryption/lib/Migration/Version1005Date20200312102456.php:52`

I removed it via occ for now.

**Comment by sunjam** [comment] 2021-03-06 15:12
Duplicate of #224 and #225

**Comment by bcutter** [comment] 2021-04-10 13:54
Now that this issue exists for more than one month and NC v21 is being pushed out, a statement would really be nice. Cause E2EE is broken for me and many others since (accidentally) updated to NC v21.
@schiessle thanks for an info.

**Closed** 2021-04-22 08:00 UTC
Labels: 0. Needs triage, enhancement
