### ISSUE TITLE
Clarifying e2e encryption mnemonic description and usage on clients devices

### ISSUE THREAD

**Issue by sunjam** [nextcloud/end_to_end_encryption#205] opened 2020-10-01 01:11 UTC
[Originally posted to Desktop client](https://github.com/nextcloud/desktop/issues/2442) repo, but should more likely be reported to this main repository.  edit: It seems people can recover the mnemonic directly from any authenticated client device.  I hope this changes via [#2443](https://github.com/nextcloud/desktop/issues/2443). :heart: 

Related to nextcloud/documentation#11274 for e2e documentation on Nextcloud desktop client. [Revoke Keys](https://github.com/nextcloud/end_to_end_encryption/issues/32) discussion and [issue for better overall documentation](https://github.com/nextcloud/documentation/issues/11274).

Please considering designing mnemonics so that will only be shown that singular time, and will disappear forever once you select _Enable encryption_.

![a5f57688e6e91b1ec7573180b5943cfdc8778f06](https://user-images.githubusercontent.com/1787238/93411222-81ae2580-f84f-11ea-80bf-15c1b3814dbd.png)

I appreciate the wording you have on 3.0.1, but it is not secure enough.  Thanks for considering.
![e8d76bb78f7d03e9995b0f16b1d56ccdaecba588](https://user-images.githubusercontent.com/1787238/93411299-b1f5c400-f84f-11ea-8232-f78ddd32daed.png)

To protect your Cryptographic Identity, we encrypt it with a mnemonic of 12 dictionary words.  You must record and never lose these 12 words.  These will never be shown again once enabled and are required in case you ever lose access to your data or wish to add other devices to your account (like your mobile phone or laptop).  Have you recorded these words?  Record them carefully then Enable encryption.

**Comment by joshtrichards** [comment] 2024-01-05 16:35
We have no interaction with the mnemonic in this repository. All of the other matters noted have their own Issues elsewhere. Closing here as a duplicate of nextcloud/desktop#2442

**Closed by joshtrichards** 2024-01-05 16:35 UTC
Labels: 0. Needs triage, enhancement, feature: activation
