### ISSUE TITLE
"Encrypted" folder contents appear under Recents menu.

### ISSUE THREAD

**Issue by ohyhyb** [nextcloud/end_to_end_encryption#121] opened 2020-02-05 15:59 UTC
Server running version 16.0.7 with Snap

Items uploaded to private folders appear under the recents menu with their original filenames and thumbnails are generated for media files. A 403 is returned when attempting to view items. There doesn't seem to be any real encryption employed here, it acts more like http basic auth.

**Comment by tobiasKaminsky** [comment] 2020-03-02 08:55
How did you uploaded them? Via Desktop and are they within an subfolder?

**Comment by georgehrke** [comment] 2020-03-12 12:02
Duplicate of https://github.com/nextcloud/desktop/issues/816

**Closed by georgehrke** 2020-03-12 12:02 UTC
