### ISSUE TITLE
encryption fails on postgresql, SELECT lastval(...', Array)

### ISSUE THREAD

**Issue by kruthoff** [nextcloud/end_to_end_encryption#55] opened 2018-02-09 10:33 UTC
I'm creating a folder with the iOS app, and then I'm trying to encrypt it. It fails (red error message appears shortly on screen). The following is logged in nextcloud.log and in nginx access.log:

``
{"reqId":"z6m8d3BO7JiN0n55Gt5j","level":3,"time":"2018-02-09T11:13:29+01:00","remoteAddr":"185.12.128.225","user":"andreas","app":"no app in context","method":"POST","url":"/nextcloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/00078863ocdjag5z8nms?format=json","message":"Exception: {"Exception":"DoctrineDBALExceptionDriverException","Message":"An exception occurred while executing 'SELECT lastval()':nnSQLSTATE[55000]: Object not in prerequisite state: 7 ERROR:  lastval is not yet defined in this session","Code":0,"Trace":"
#0 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): DoctrineDBALDriverAbstractPostgreSQLDriver->convertException('An exception oc...', Object(DoctrineDBALDriverPDOException))
#1 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): DoctrineDBALDBALException::driverExceptionDuringQuery(Object(DoctrineDBALDriverPDOPgSqlDriver), Object(DoctrineDBALDriverPDOException), 'SELECT lastval(...', Array)
#2 /var/www/html/nextcloud/lib/private/DB/Connection.php(195): DoctrineDBALConnection->executeQuery('SELECT lastval(...', Array, Array, NULL)
#3 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(541): OCDBConnection->executeQuery('SELECT lastval(...', Array, Array)
#4 /var/www/html/nextcloud/lib/private/DB/AdapterPgSql.php(29): DoctrineDBALConnection->fetchColumn('SELECT lastval(...')
#5 /var/www/html/nextcloud/lib/private/DB/Connection.php(234): OCDBAdapterPgSql->lastInsertId('oc_e2e_encrypti...')
#6 /var/www/html/nextcloud/lib/public/AppFramework/Db/Mapper.php(127): OCDBConnection->lastInsertId('oc_e2e_encrypti...')
#7 /var/www/html/nextcloud/apps/end_to_end_encryption/lib/LockManager.php(95): OCPAppFrameworkDbMapper->insert(Object(OCAEndToEndEncryptionDbLockEntity))
#8 /var/www/html/nextcloud/apps/end_to_end_encryption/lib/Controller/RequestHandlerController.php(481): OCAEndToEndEncryptionLockManager->lockFile(78863, '')
#9 [internal function]: OCAEndToEndEncryptionControllerRequestHandlerController->lockFolder(78863, '')
#10 /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(161): call_user_func_array(Array, Array)
#11 /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(91): OCAppFrameworkHttpDispatcher->executeController(Object(OCAEndToEndEncryptionControllerRequestHandlerController), 'lockFolder')
#12 /var/www/html/nextcloud/lib/private/AppFramework/App.php(115): OCAppFrameworkHttpDispatcher->dispatch(Object(OCAEndToEndEncryptionControllerRequestHandlerController), 'lockFolder')
#13 /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OCAppFrameworkApp::main('OCAEndToEndEnc...', 'lockFolder', Object(OCAppFrameworkDependencyInjectionDIContainer), Array)
#14 [internal function]: OCAppFrameworkRoutingRouteActionHandler->__invoke(Array)
#15 /var/www/html/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OCAppFrameworkRoutingRouteActionHandler), Array)
#16 /var/www/html/nextcloud/ocs/v1.php(78): OCRouteRouter->match('/ocsapp/apps/en...')
#17 /var/www/html/nextcloud/ocs/v2.php(24): require_once('/var/www/html/n...')
#18 {main}","File":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php","Line":92}","userAgent":"Mozilla/5.0 (iOS) Nextcloud-iOS/2.20.0","version":"13.0.0.14"}
``

``
185.12.128.225 - andreas [09/Feb/2018:11:13:29 +0100] "POST /nextcloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/00078863ocdjag5z8nms?format=json HTTP/2.0" 404 1297 "-" "Mozilla/5.0 (iOS) Nextcloud-iOS/2.20.0"
127.0.0.1 - andreas [09/Feb/2018:11:13:29 +0100] "POST /nextcloud/ocs/v2.php/apps/end_to_end_encryption/api/v1/lock/00078863ocdjag5z8nms?format=json HTTP/1.0" 404 228 "-" "Mozilla/5.0 (iOS) Nextcloud-iOS/2.20.0"
``

**Comment by kruthoff** [comment] 2018-02-10 22:15
I‘m using postgresql as database.

**Comment by SonRiab** [comment] 2018-02-13 21:22
Okay, I think we need an additional autoincremented column to avoid problems with postgresql here. I can confirm this issue on my installation too.

**Comment by tobiasKaminsky** [comment] 2018-02-14 11:05
@schiessle this seems to be database related and not iOS related

**Comment by schiessle** [comment] 2018-03-07 12:05
@kruthoff @SonRiab could you test if this solves the problem for you https://github.com/nextcloud/end_to_end_encryption/pull/64 ? You can skip the test files and only replaces the LockMapper.php on your system. Thanks!

**Comment by kruthoff** [comment] 2018-03-07 19:41
Problem solved! Thanks a lot!

**Comment by schiessle** [comment] 2018-03-08 09:48
@kruthoff thanks for testing... I will merge it and prepare a new release for the app store soon

**Comment by schiessle** [comment] 2018-03-08 09:49
will be released with 1.0.5

**Closed by schiessle** 2018-03-08 09:49 UTC
