### ISSUE TITLE
upload/download broken for desktop sync client with E2EE app enabled

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/end_to_end_encryption#159] opened 2020-05-31 07:51 UTC
Yesterday I reported a bug for the Desktop Sync Client (v2.6.4) which still doesn't sync any file If this app is enabled on the server. Even for non-encrypted folders. And that totaly prevent me from using this wonderful app that I really want to use.

And I really don't know if this is a bug only for the client app or only also for the server app.

With this issue I hope that there can be implemented something like a workaround that the client app sync again. Because there aren't developer for the client app, it could take month or years until this bug is finally fixed.

The issue where you can get all relevant informations:
https://github.com/nextcloud/desktop/issues/2050

If you need infos about the the Nextcloud server (tried with v19.0.0.11 and 18.0.4.2, no errors in the log file btw):
Link: https://schedelcloud.ddnss.de/index.php/s/xT4TiPf3rNPrHfW
Passwort: DWBu++U1l/X/kmWPnBvU

Would it be possible to implmenent something in this app that helps the (maybe buggy) client app to still sync even with E2EE app enabled on the server?

**Comment by georgehrke** [comment] 2020-05-31 10:57
Duplicate of https://github.com/nextcloud/desktop/issues/2050

Please do not open duplicate reports in different repos.
If it's a sync problem in the desktop client, it should be triaged there first. If it later turns out to be an issue of this app, we will move the issue here. Duplicate issues only cause more work and do not speed anything up.

**Closed by georgehrke** 2020-05-31 10:57 UTC
Labels: 0. Needs triage, bug
