### ISSUE TITLE
Version 1.1 Still Shows As Incompatible w/ Nextcloud 15

### ISSUE THREAD

**Issue by Nixon506E** [nextcloud/end_to_end_encryption#91] opened 2018-12-16 15:56 UTC
The store version of this app is 1.1.0 but the description still states a necessary server of version 14 or lower and won't let me enable this app.

**Comment by tobiasKaminsky** [comment] 2018-12-17 07:42
@schiessle

**Comment by psmith135** [comment] 2019-01-24 09:13
I would appreciate any update on this issue. Just updated to current stable 15.0.2 (available for 2 weeks now) and cannot access my E2E encrypted files any more. Get this error messages:

**
Following apps have been disabled: end_to_end_encryption (incompatible)

This app cannot be installed because the following dependencies are not fulfilled:
Server version 14 or lower is required.
**

**Comment by schiessle** [comment] 2019-01-29 11:06
Can you check the info.xml (apps/end_to_end_encryption/appinfo/info.xml) and double check that the version is 1.1.0 and that "min-version" and "max-version" is set to 15?

I just downloaded the package directly from the app strore and it shows the right min/max version.

**Comment by dmaroulidis** [comment] 2019-02-11 18:13
I have the same issue. Just upgraded to Nextcloud 15.0.4 and updated the app to 1.1.0. I checked the "min-version" and "max-version" and they 're set to 15, but I still cannot enable the app because the description says that version 14 or lower is required.

**Comment by DiabolusExMachina** [comment] 2019-08-24 14:52
Is this Plugin the only way to archive end to end encyrption? I just rented a Nextcloud Server but if end to end decrpytion is not working the purcharse would be pointless... 

Is there any way to get this working? Maybe downgrade somehow to an old version? Or is there a different working app for end to end encryption?

**Comment by georgehrke** [comment] 2020-03-12 13:15
Duplicate of https://github.com/nextcloud/end_to_end_encryption/issues/117

**Closed by georgehrke** 2020-03-12 13:15 UTC
Labels: integration
