### ISSUE TITLE
E2E breaks client connection

### ISSUE THREAD

**Issue by mickare** [nextcloud/end_to_end_encryption#87] opened 2018-11-30 12:08 UTC
When enabling the E2E encryption the Nextcloud client will refuse to connect.

Server: Nextcloud 14.0.3
Client: Latest (2.5.0git)

### Logs:
Client: https://gist.github.com/mickare/36ca4cf633c5316fd675d8c752d9686c
Server: *missing* (I am using a managed Nextcloud Instance without access to Server Log files.)

### Related issue:
https://github.com/nextcloud/desktop/issues/830

**Comment by tobiasKaminsky** [comment] 2018-11-30 12:36
@camilasan

**Comment by AnwariasEu** [comment] 2018-11-30 13:01
Same problem here. User authentication, e.g. adding a new account works fine but syncing gives a `No connection to Nextcloud at`

Server: 14.0.4-1
Client: 2.5.0-4, also with appimage-daily from 29.11.2018

Can provide server logs if required.

**Comment by dirkhusemann** [comment] 2018-12-28 13:22
Same problem with Nextcloud 15.0.0 stable and client 2.5.1final (build 20181204).

**Comment by mickare** [comment] 2018-12-28 15:49
More related issues:
- https://github.com/nextcloud/desktop/issues/977
- https://github.com/nextcloud/desktop/issues/868
- https://github.com/nextcloud/desktop/issues/560

**Comment by mickare** [comment] 2018-12-28 16:47
Seems to be a desktop client issue.

Workaround here: https://github.com/nextcloud/desktop/issues/560

**Comment by mickare** [comment] 2019-03-08 16:22
Issue was resolved for me with newer versions.

Server: Nextcloud 15.0.5
Client: 2.5.1final (build 20181204)

@dirkhusemann How is it on your end?

**Comment by basvandenbrink** [comment] 2019-03-08 17:04
@mickare I am also running Nextcloud 15.0.5 and client version 2.5.1, but enabling the End-to-End Encryption app still results in the client not being able to connect to the server.

**Comment by camilasan** [comment] 2019-09-15 15:26
Please, try the daily build from tonight, #1420 is merged and it might fix it :)

**Comment by DominiqueFuchs** [comment] 2019-09-25 14:07
Duplicate of original issue [desktop/#830](https://github.com/nextcloud/desktop/issues/830) and fixed by [desktop/PR#1420](https://github.com/nextcloud/desktop/pull/1420)

**Closed by DominiqueFuchs** 2019-09-25 14:07 UTC
Labels: 4. to release, bug
