### ISSUE TITLE
"Limit to groups" input field gone after fiddling around

### ISSUE THREAD

**Issue by ristein** [nextcloud/end_to_end_encryption#404] opened 2023-03-20 10:22 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Steps to reproduce
1. enable E2EE-app
2. under /settings/admin/security: limit to one group, save
3. select all groups, save
4. deselect all groups, save

### Expected behaviour
look like before those changes

### Actual behaviour
Android app says "E2EE disabled on server" when trying to access encrypted folders.
input field is gone:

![image](https://user-images.githubusercontent.com/55446611/226305370-a801562f-5a42-4d8e-ae8b-eb0bee2ccf37.png)

after step 2. I was using E2EE just fine. Then I wanted to allow all users to access this feature, but could not.
I already tried clicking "save", dis-/enabling/removing E2EE-app, light & dark theme.

### Server configuration

**Operating system:** Ubuntu 22.04 LTS

**Web server:** Apache/2.4.56 (Ubuntu) OpenSSL/3.0.2

**Database:** mysql  Ver 15.1 Distrib 10.6.12-MariaDB

**PHP version:** PHP 8.1.17

**Nextcloud version:** Nextcloud Hub 3 (25.0.4), tested also Hub 4 now

**Updated from an older Nextcloud/ownCloud or fresh install:** updating since installed a year ago

**Where did you install Nextcloud from:** https://docs.nextcloud.com/server/latest/admin_manual/installation/example_ubuntu.html

**Signing status:**
No errors have been found.

**List of activated apps:**
  - end_to_end_encryption: 1.11.1
<details>
<summary>Apps list</summary>

```
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - approval: 1.0.12
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.4
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.2.0
  - contactsinteraction: 1.6.0
  - cookbook: 0.10.1
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - end_to_end_encryption: 1.11.1
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_accesscontrol: 1.15.1
  - files_automatedtagging: 1.15.2
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - forms: 3.2.0
  - jitsi: 0.16.2
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - onlyoffice: 7.6.8
  - password_policy: 1.15.0
  - photos: 2.0.1
  - polls: 4.1.8
  - previewgenerator: 5.2.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - quota_warning: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.4
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_migration: 3.0.0
  - user_status: 1.5.0
  - user_usage_report: 1.10.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - welcome: 1.0.8
  - workflowengine: 2.7.0
Disabled:
  - encryption
  - group_default_quota: 0.1.6
  - ransomware_protection: 1.14.0
  - socialsharing_email: 2.5.0
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "127.0.0.1",
            "cloud.example.com",
            "192.168.1.xx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.4.1",
        "overwrite.cli.url": "https:\/\/cloud.example.com",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "allow_local_remote_servers": true,
        "maintenance": false,
        "default_phone_region": "DE",
        "theme": "",
        "loglevel": 0,
        "preview_max_x": 4096,
        "preview_max_y": 4096,
        "jpeg_quality": "70",
        "trashbin_retention_obligation": "31, 32",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "cookbook",
            "jitsi",
            "user_usage_report"
        ]
    }
}

```
</details>

**Are you using external storage, if yes which one:** local, but not for E2EE-folders

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** tried multiple: Firefox, incognito tab, fennec (firefox mobile)

**Operating system:** Windows, Android

#### Web server error log
I don't do logs. Error log does not log anything when accessing /settings/admin/security

#### Nextcloud log (data/nextcloud.log)
Nothing in here since I first installed E2EE-app

#### Browser log
is this relevant?

**Comment by discounter24** [comment] 2023-03-27 11:37
Same problem. I found some js errors browser console:

## Example
<details>
    <summary>Click me</summary>

Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). content-script-start.js:7408:11
GEThttps://REDACTED/apps/theming/image/background?v=7
[HTTP/3 404 Not Found 100ms]

TypeError: Object.entries(...).find(...) is undefined
    data settings-vue-settings-admin-security.js:1
    VueJS 6
    74459 settings-vue-settings-admin-security.js:1
    r settings-vue-settings-admin-security.js:1
    s settings-vue-settings-admin-security.js:1
    O settings-vue-settings-admin-security.js:1
    <anonymous> settings-vue-settings-admin-security.js:1
    <anonymous> settings-vue-settings-admin-security.js:1
vue.runtime.esm.js:3018:57
    VueJS 8
    74459 settings-vue-settings-admin-security.js:1
    r settings-vue-settings-admin-security.js:1
    s settings-vue-settings-admin-security.js:1
    O settings-vue-settings-admin-security.js:1
    <anonymous> settings-vue-settings-admin-security.js:1
    <anonymous> settings-vue-settings-admin-security.js:1
TypeError: t is null
    isSelected https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    optionHighlight https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    r https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    te https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    r https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    _render https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    r https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    get https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    t https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    mount https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    $mount https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    init https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    f https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    f https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    Uo https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    _update https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    r https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    get https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    t https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    mount https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    $mount https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    init https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    f https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    f https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    m https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    f https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    Uo https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    _update https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    r https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    get https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    t https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    mount https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    $mount https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    init https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    f https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    f https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    Uo https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    _update https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    r https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    get https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    t https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    mount https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    $mount https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    <anonymous> https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    <anonymous> https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    <anonymous> https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
end_to_end_encryption-adminSettings.js:1:881250
TypeError: this.$el.querySelector is not a function
    updateWidth https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    mounted https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    je https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    sn https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    insert https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    k https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    Uo https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    _update https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    r https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    get https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    t https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    mount https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    $mount https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    <anonymous> https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    <anonymous> https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    <anonymous> https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
end_to_end_encryption-adminSettings.js:1:881250
TypeError: this.$el.setAttribute is not a function
    r https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    je https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    sn https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    insert https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    k https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    Uo https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    _update https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    r https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    get https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    t https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    mount https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    $mount https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    <anonymous> https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    <anonymous> https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    <anonymous> https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
end_to_end_encryption-adminSettings.js:1:881250
TypeError: this.$el.querySelector is not a function
    updateWidth https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    value https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    je https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    run https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    yn https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    Ge https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    $e https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    promise callback*Ie https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    Ge https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    bn https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    update https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    notify https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    set https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    set https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    mounted https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    je https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    sn https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    mount https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    $mount https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    <anonymous> https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    <anonymous> https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    <anonymous> https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
end_to_end_encryption-adminSettings.js:1:881250
TypeError: t is null
    isSelected https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    optionHighlight https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    r https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    te https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    r https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    _render https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    r https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    get https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    run https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    yn https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    Ge https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    $e https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    promise callback*Ie https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    Ge https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    bn https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    update https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    notify https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    set https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    set https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    mounted https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    je https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    sn https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    mount https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    $mount https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    <anonymous> https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    <anonymous> https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    <anonymous> https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
end_to_end_encryption-adminSettings.js:1:881250
GEThttps://REDACTED/apps/theming/image/background?v=7
[HTTP/3 404 Not Found 110ms]

TypeError: e is null
    valueKeys https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    valueKeys https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    get https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    evaluate https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    Zn https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    isSelected https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    optionHighlight https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    r https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    te https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    r https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    _render https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    r https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    get https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    run https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    yn https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    Ge https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    $e https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    promise callback*Ie https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    Ge https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    bn https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    update https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    notify https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    set https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    set https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    t https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    c https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    w https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    b https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    kh https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    i https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    promise callback*kh https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    i https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    searchGroup https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    e https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    searchGroup https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    l https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    setTimeout handler*u https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    mounted https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    je https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    sn https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    mount https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    $mount https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    <anonymous> https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    <anonymous> https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
    <anonymous> https://REDACTED/custom_apps/end_to_end_encryption/js/end_to_end_encryption-adminSettings.js?v=1134dfa3-7:1
end_to_end_encryption-adminSettings.js:1:881250

</details

**Comment by ristein** [comment] 2023-03-27 16:26
great to hear, I'm not the only one.
I found a workaround mentioned here: https://github.com/nextcloud/server/issues/5539#issuecomment-1085717171
I disabled & removed the app, used following command to remove the setting in database and reinstalled.
`sudo -u www-data /usr/bin/php /var/www/nextcloud/occ config:app:delete end_to_end_encryption allowed_groups`
removing might not be necessary.

**Comment by discounter24** [comment] 2023-03-27 18:08
Thanks a lot. That worked.  Removing/deactivating is indeed not necessary.

**Comment by manuquadrat** [comment] 2023-05-07 10:18
I have a very similar issue since upgrading to Nextcloud 25 (25.0.5) (E2EE: 1.11.3). The "limit to group" setting is not available and the option for end users to reset E2EE also disappeared. Unfortunately, the mentioned command to remove the setting from the database did not work for me, also removing and re-installing the E2EE App did not help.

**Comment by joshtrichards** [comment] 2023-11-21 14:10
I cannot reproduce this in v27.1.3. Closing. If anyone is still experiencing this, this can get re-opened.

**Closed by joshtrichards** 2023-11-21 14:10 UTC
Labels: 0. Needs triage, bug, feature: settings
