### ISSUE TITLE
app E2E is not yet compatible with nextcloud 16?

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/end_to_end_encryption#110] opened 2019-05-16 09:12 UTC
I noticed that since I updated nextcloud to version 16.0.0, today I updated to 16.0.1

the E2E plugin is still not compatible with this release as ever?

Is there any problem?

will there be an update soon or should we wait?

I have always activated an unverified application, or if I delete it it will not allow me to install it

![Immagine](https://user-images.githubusercontent.com/35575744/57841756-6fd7f080-77cb-11e9-8025-4bff103167f0.png)

**Comment by tobiasKaminsky** [comment] 2019-05-16 09:32
@nextcloud/server-triage

**Comment by nickvergessen** [comment] 2019-05-16 09:41
Duplicate of #108

**Closed by nickvergessen** 2019-05-16 09:41 UTC
