### ISSUE TITLE
Request failure: forbidden (403)

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/end_to_end_encryption#50] opened 2018-02-07 11:59 UTC
Hi, I am not even sure if this is an error related to the e2ee app, server config or the latest iOS beta app. 

I can create folders using the iOS app,
I can encrypt the folders using the iOS app,
the folder gets successfully marked as being encrypted (visible in webUI and iOS app),
but when I try to upload files into that encrypted folder using the iOS app I get the 403 forbidden error. 

When looking into the server logs, I find 
"OCA\DAV\Connector\Sabre\Exception\Forbidden: client not allowed to access end-to-end encrypted content"

I'd be happy to help with debugging but need some advice what to do.

NC 13
E2EE 1.0.2
iOS app: 2.19.2.00020

**Comment by tobiasKaminsky** [comment] 2018-02-07 15:53
@schiessle this is the same arror as in #43, but I am unsure what the problem is.
Could the user agent be wrong?

**Comment by schiessle** [comment] 2018-02-07 16:10
yes, looks like a problem with the user agent string

**Comment by marinofaggiana** [comment] 2018-02-07 16:10
I think that the issue is the version number detect .. 2.20.0 for server side but in testflight this version in < of 2.20.0 ...

**Comment by schiessle** [comment] 2018-02-07 16:11
> I think that the issue is the version number detect .. 2.20.0 for server side but in testflight this version in < of 2.20.0 ...

Make sense. You already released a version >= 2.20.0, right? So the solution would to update the iOS app.

**Comment by marinofaggiana** [comment] 2018-02-07 16:14
Soon i release the 2.20.0 with E2E in (experimental mode) on App Store ... please be patient.

**Comment by ho1ger** [comment] 2018-02-07 16:37
Maybe another hint that might be helpful: I found this issue not only with the latest versions of the e2ee app and the iOS NC app. I experienced the exact same behavior since the first version of the iOS NC app with e3ee support was released. So in fact this never worked for me.

You can exclude that this is not an nginx server configuration problem?

**Comment by schiessle** [comment] 2018-02-07 16:43
The server checks for the iOS client version >= 2.20.0 to block older clients which don't implement e2ee. So I'm quite sure that the problem is that 2.20.0 is not released yet. Sorry for the inconvenience, we thought that 2.20.0 will be released together/before Nextcloud 13

**Closed** 2018-02-15 10:46 UTC
