### ISSUE TITLE
Double prompt to setup e2ee passphrase.

### ISSUE THREAD

**Issue by ph00lt0** [nextcloud/end_to_end_encryption#248] opened 2021-08-13 16:48 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Steps to reproduce
1. Install the end to end encryption app
2. Setup a passphrase on MacOS
3. Create a new folder
4. Enable encryption for this folder
5. Open android app
6. Click on newly created folder
7. You will be prompted to setup passphrase again.

### Expected behaviour
I should only be prompted once to setup a passphrase. 

### Actual behaviour
Now I can sync e2ee encrypted files from 2 devices with a different encryption within the same account, very useless. My macbook syncs data with another key as the android client and there is no way to reset this, or change this.

### Server configuration

**Operating system:**
Nextcloud snap on Ubuntu 21

**Nextcloud version:** (see Nextcloud admin page)
21.0.3

### Logs
I obviously can't share full logs and debugging. But there is an fatal error: ```Failed to handle NewFileInfoEvent .``` and the following error happens when I create a document in the folder: ```OCP\Files\NotFoundException```

**Comment by ph00lt0** [comment] 2021-08-13 17:04
When uploading files from android, in the client I get a connection error. In the logs it shows the following:
```OCA\EndToEndEncryption\Exceptions\MissingMetaDataException: Intermediate meta-data file missing```

**Comment by ph00lt0** [comment] 2021-08-13 17:07
My guess is that the "solution" for crashed setups of this app actually do not work sufficiently. https://github.com/nextcloud/end_to_end_encryption/issues/32

We really need a way to reset the app data fully.

**Comment by asheroto** [comment] 2021-11-12 23:53
This happening for me as well.

**Comment by bcutter** [comment] 2022-01-29 15:36
> Uninstalled and reinstalled the client. Now it just says "display mnemonic"... does that mean E2EE is working now?

If you actually see your mnemonic once clicking that button, that's a good indicator E2EE has been setup for that endpoint/client.

**Comment by joshtrichards** [comment] 2024-01-05 16:30
> Open android app
> Click on newly created folder
> You will be prompted to setup passphrase again

This could have been an Android client issue. It sounds like it was. Probably not an issue here with this app.

> Now I can sync e2ee encrypted files from 2 devices with a different encryption within the same account, very useless. My macbook syncs data with another key as the android client and there is no way to reset this, or change this.
[...]
> We really need a way to reset the app data fully.

That was added in #305.

No idea for sure how you ended up with the conflict between the clients and virtually impossible to try to reproduce without the exact same client versions you had in place at the time. A lot of E2EE code has changed in each of the clients since this report. In addition the clients are more proactively informed now if keys already exist for a user (e.g. #360) even before attempting to add new keys.

If you can reproduce this behavior still today, please provide the server-app and client versions involved.

**Comment by joshtrichards** [comment] 2024-01-05 20:49
Fair enough.

> 3 years later someone replies, this must be a joke.

Nextcloud is a large open source project spread across hundreds of repositories. Limited resources and many of us are volunteers.

Timely, individualized responses to every bug report aren't particularly realistic via this channel.

Even so, matters are often addressed, without  developers getting the opportunity to follow-up on every potentially relevant or overlapping issue in the backlog personally and in real time (there are other channels with SLAs available for that).

I happen to be triaging the old backlog and attempting to identify some of the matters that have already been addressed in the code base or in the clients (i.e. the bug was never here in this app since the bulk of the implementation is in the clients). Or those that need improved documentation or to be moved to more appropriate places (like one of the clients involved) in order to o get the correct eyes on them.

I'm going to close this Issue, since there's nothing remaining that is actionable. Thanks for reporting the issue originally. I'm sorry things didn't work out.

**Closed** 2024-01-05 20:50 UTC
Labels: 0. Needs triage, bug, needs info, client: 💻 desktop, client: 🤖🍏 mobile, feature: activation

**Comment by asheroto** [comment] 2024-01-05 21:55
@joshtrichards thanks for the insight into the org. I know that Issues aren't really a place to discuss this, but was curious does Nextcloud Enterprise have a separate development team or do they work with the volunteers?
